version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  database:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

  mongodb:  # Added MongoDB service here
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongodb_data:/data/db  # Persist data

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  # api-gateway:
  #   build:
  #     context: ./api-gateway
  #   container_name: api-gateway
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  #     DATABASE_URL: postgres://admin:password@database:5432/mydb
  #   depends_on:
  #     - rabbitmq
  #     - database

  # order-service:
  #   build:
  #     context: ./order-service
  #   ports:
  #     - "3001:3000"
  #   container_name: order-service
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  #     DATABASE_URL: postgres://admin:password@database:5432/mydb
  #   depends_on:
  #     - rabbitmq
  #     - database

  # payment-service:
  #   build:
  #     context: ./payment-service
  #   ports:
  #     - "3002:3000"
  #   container_name: payment-service
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq

  # notification-service:
  #   build:
  #     context: ./notification-service
  #   ports:
  #     - "3003:3000"
  #   container_name: notification-service
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq

  # log-service:
  #   build:
  #     context: ./log-service
  #   ports:
  #     - "3006:3000"
  #   container_name: log-service
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq

  # inventory-service:
  #   build:
  #     context: ./inventory-service
  #   ports:
  #     - "3004:3000"
  #   container_name: inventory-service
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq

  # user-service:
  #   build:
  #     context: ./user-service
  #   ports:
  #     - "3005:3000"
  #   container_name: user-service
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq

volumes:
  db_data: {}  # Define the volume for PostgreSQL
  mongodb_data: {}  # Ensure this volume is defined for MongoDB
